<a href="https://colab.research.google.com/github/MasakazuNaganuma/numpy-100/blob/master/100_Numpy_exercises_naga.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

# 100のnumpyエクササイズ

numpyのメーリングリスト、スタックオーバーフローで集めた演習問題集です。
と numpy ドキュメントの中にあります。このコレクションの目的は、古い
と新しいユーザーのためだけでなく、教える人のための演習セットを提供します。


もしあなたがエラーを見つけたり、それらのいくつかを解決するためのより良い方法を持っていると思うならば、感じてください。
<https://github.com/rougier/numpy-100>で自由に課題を公開してください。

File automatically generated. See the documentation to update questions/answers/hints programmatically.

ファイルは自動的に生成されます。プログラムで質問/回答/ヒントを更新するには、ドキュメントを参照してください。

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

`inititialize.py` モジュールを実行して、各質問に対して
質問番号 `n` に対して `hint(n)` または `answer(n)` を指定します。

In [0]:
!git clone https://github.com/MasakazuNaganuma/numpy-100.git numpy-100

Cloning into 'numpy-100'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 696 (delta 2), reused 0 (delta 0), pack-reused 690
Receiving objects: 100% (696/696), 362.44 KiB | 4.71 MiB/s, done.
Resolving deltas: 100% (395/395), done.


In [0]:
!ls

100_Numpy_exercises.ipynb			  initialise.py
100_Numpy_exercises.md				  LICENSE.txt
100_Numpy_exercises_with_hints.md		  numpy-100
100_Numpy_exercises_with_hints_with_solutions.md  README.md
100_Numpy_exercises_with_solutions.md		  requirements.txt
100_Numpy_random.ipynb				  source
generators.py


In [0]:
cd /content/numpy-100

/content/numpy-100


In [0]:
pip install generators

In [0]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

#### 1. numpyパッケージを `np` (★☆☆☆) という名前でインポートします。

In [0]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

#### 2. numpyのバージョンと設定を表示する(★☆☆)

In [0]:
print(np.__version__)

1.18.3


#### 3. Create a null vector of size 10 (★☆☆)

#### 3. サイズ10のヌルベクトルを作成します。(★☆☆)

In [0]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)
#### 4.配列のメモリサイズを調べる方法 (★☆☆)

In [0]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 5. numpy add関数のドキュメントをコマンドラインから取得するには？(★☆☆)

In [0]:
np.info(np.add)

In [0]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 6. サイズ10のNULLベクトルを作成しますが、5番目の値が1になっています。(★☆☆)

In [0]:
a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
#### 7. 10から49までの値を持つベクトルを作成します。 (★☆☆)


In [0]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)
#### 8. ベクトルを反転させる(最初の要素が最後になる) (★☆☆)

In [0]:
a = a[::-1]
a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#### 9. 0から8までの値を持つ3×3の行列を作成する(★☆☆)
https://note.nkmk.me/python-list-array-numpy-ndarray/



In [0]:
a = np.arange(0,9)
a = a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#### 10. [1,2,0,0,4,0]から0以外の要素のインデックスを求める(★☆☆)

In [0]:
a = np.array([1,2,0,0,4,0])
print('a=',a)
b = np.nonzero(a)
print('b=',b)

a= [1 2 0 0 4 0]
b= (array([0, 1, 4]),)


In [0]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)
#### 11. 3×3の単位行列を作成する(★☆☆)

In [0]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)
#### 12. 乱数値で3×3×3の配列を作る(★☆☆)
https://note.nkmk.me/python-numpy-random/

In [0]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.44958713 0.10042666 0.37590076]
  [0.41231153 0.76973708 0.0856797 ]
  [0.62018438 0.63331444 0.2751072 ]]

 [[0.74033568 0.90796037 0.07941157]
  [0.47215868 0.96987341 0.32346675]
  [0.60667084 0.35887729 0.90186506]]

 [[0.3963644  0.32144455 0.57421224]
  [0.43264524 0.21680322 0.81339769]
  [0.88510745 0.93031361 0.52086589]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#### 13. 乱数値で10×10の配列を作成し、最小値と最大値を求める(★☆☆)

In [0]:
a = np.random.random((10,10))
print('a=',a)
print('max=',a.max())
print('min=',a.min())

a= [[0.79260727 0.2740864  0.20800442 0.92665974 0.91286352 0.04682143
  0.51529579 0.26330203 0.91833048 0.07907453]
 [0.96195635 0.56940648 0.88037102 0.6888     0.62204267 0.05811918
  0.39937054 0.3609624  0.50923354 0.98379756]
 [0.53440078 0.36045557 0.19757205 0.38400048 0.3287758  0.86677075
  0.25864609 0.71391161 0.86191354 0.03345308]
 [0.54629307 0.98004706 0.04996117 0.95402886 0.58374475 0.87430161
  0.18721273 0.72510055 0.86899737 0.49329633]
 [0.93267366 0.51664997 0.17140198 0.58928405 0.4073935  0.95734164
  0.99971459 0.45322873 0.93734779 0.27129307]
 [0.52125448 0.00924633 0.10550745 0.41924304 0.88413647 0.88431886
  0.54131266 0.25874266 0.98943675 0.67203382]
 [0.33821403 0.8277686  0.91533432 0.60704785 0.15870219 0.64664341
  0.21497499 0.316533   0.34574072 0.91008911]
 [0.18391894 0.87485617 0.90010068 0.55925774 0.1330447  0.47738366
  0.36610797 0.96271472 0.72023225 0.65094447]
 [0.54920088 0.33713711 0.5311479  0.51038433 0.16108353 0.27705986
  0.07637

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
#### 14. サイズ30のランダムなベクトルを作成し、その平均値を求めます。(★☆☆)

In [0]:
a = np.random.random((30))
print('a size=',a.size)
b = a.mean()
print(b)

a size= 30
0.5091630655181874


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
#### 15. 境界線に1、内側に0の2次元配列を作成します(★☆☆)

In [0]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0   #Z[1:9,1:9] = 0 と同じ意味
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
#### 16. 既存の配列の周りにボーダー（0で塗りつぶされた）を追加するには？(★☆☆)
https://qiita.com/horitaku1124/items/6ae979b21ddc7256b872

http://arduinopid.web.fc2.com/Q5-16.html

In [0]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [0]:
a = np.ones((5,5))
print(a)
print()
a[:,0] = 0
a[:,4] = 0
a[0,:] = 0
a[4,:] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [0]:
a = np.zeros((5,5))
a[1:-1,1:-1] = 1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
#### 17. 次の式の結果は？(★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [0]:
print('(0 * np.nan) = ', 0 * np.nan)
print('(np.nan == np.nan) = ', np.nan == np.nan)
print('(np.inf > np.nan) = ', np.inf > np.nan)
print('(np.nan - np.nan) = ', np.nan - np.nan)
print('(np.nan in set([np.nan])) = ', np.nan in set([np.nan]))
print('(0.3 == 3 * 0.1) = ', 0.3 == 3 * 0.1)

(0 * np.nan) =  nan
(np.nan == np.nan) =  False
(np.inf > np.nan) =  False
(np.nan - np.nan) =  nan
(np.nan in set([np.nan])) =  True
(0.3 == 3 * 0.1) =  False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#### 18. 対角線のすぐ下に値1,2,3,4を持つ5x5の行列を作成します(★☆☆)
https://note.nkmk.me/python-numpy-diag-diagonal/

In [0]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [0]:
a = np.zeros((5,5))
a[1,0] = 1
a[2,1] = 2
a[3,2] = 3
a[4,3] = 4
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
#### 19. 8×8の行列を作り、市松模様で塗りつぶす(★☆☆)

In [0]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1 #奇数行に１を代入
Z[::2,1::2] = 2 #偶数行に１を代入
print(Z)

[[0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]]


In [0]:
a = np.zeros((8,8),dtype=int)
print(a)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [0]:
a[0::2,::2] = 1
print(a)

[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


In [0]:
a[1::2,1::2] = 2
print(a)

[[1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]
 [1 0 1 0 1 0 1 0]
 [0 2 0 2 0 2 0 2]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
#### 20. (6,7,8)形の配列を考えてみましょう。100番目の要素のインデックス（x、y、z）は何ですか？
https://qiita.com/tktktks10/items/f85aeef3321f6cbbd368

In [0]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [0]:
a = np.arange(6*7*8)
b = a.reshape(6,7,8)
print(b)
print(np.unravel_index(99,b.shape))

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
#### 21. タイル機能を使って市松模様の8×8の行列を作成する(★☆☆)
https://note.nkmk.me/python-numpy-tile/

In [0]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [0]:
a = ((0,1),(1,0))
np.tile(a,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)
#### 22. 5x5のランダム行列を正規化する(★☆☆)
hint: (x -mean)/std

In [0]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.34971148 -0.7496255   1.78761401 -1.778259   -0.75031712]
 [-0.86116783  0.17925156 -0.60355791  1.28183879  1.86518528]
 [ 0.62544902 -0.01734063  0.26714552  0.94197934  0.35810245]
 [-1.69571409 -0.23325409 -0.12659716  0.18963857 -0.81234041]
 [-1.24051176 -0.56241145 -0.58283427 -0.26404532  1.43206051]]


In [0]:
a = np.random.random((5,5))
a = (a - np.mean(a)) / np.std(a)
print(a)

[[-1.176044   -1.1705653   0.69145165  0.39791875  1.39806011]
 [-0.20463846 -1.45347923  0.11793505  0.01579679 -1.25026623]
 [ 1.60663579  0.64988955  0.143773   -0.74950464 -0.07834476]
 [ 1.64109923  0.83843699 -1.38149012 -0.28541238  1.30189283]
 [ 1.56826112 -0.13897588 -0.82508358 -0.22964254 -1.42770374]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
#### 23. 色を4つの符号なしバイト(RGBA)で記述するカスタムdtypeを作成します(★☆☆)

In [3]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)